apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: default
  selfLink: /api/v1/namespaces/default/services/backend-frontend-svc
spec:
  ports:
  - port: 8100
    # protocol: TCP
    targetPort: 80
    name: "8100"
  selector:
    service: frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
